version: 2.1
orbs:
  slack: circleci/slack@3.4.2
commands:
  npm_install_from_cache:
    description: "npm install and save cache"
    steps:
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    description: "Build Docusaurus project"
    steps:
      - run:
          name: Building Docusaurus project
          command: npm run build

  versioning:
    description: "Versioning the image"
    parameters:
      version_name:
        type: string
        default: "staging"
    steps:
      - run:
          name: Tag build
          command: echo "<< parameters.version_name >> $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > build/version

  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for api.deriv.com with version *$(cat build/version)*"
          success_message: "Release succeeded for api.deriv.com with version *$(cat build/version)*"
          webhook: ${SLACK_WEBHOOK}
  publish_to_pages_staging:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            npm i wrangler@2.0.19
            cd build
            npx wrangler pages publish . --project-name=deriv-developers-portal-pages --branch=staging
            echo "New staging website - https://staging-api.deriv.com/"

  publish_to_pages_production:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (production)"
          command: |
            npm i wrangler@2.0.19
            cd build
            npx wrangler pages publish . --project-name=deriv-developers-portal-pages --branch=main
            echo "New website - https://api.deriv.com"

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install_from_cache
      - build

  release_staging:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install_from_cache
      - build
      - versioning
      - publish_to_pages_staging
      - notify_slack
    environment:
      NODE_ENV: staging

  release_production:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install_from_cache
      - build
      - versioning:
          version_name: production
      - publish_to_pages_production
      - notify_slack
    environment:
      NODE_ENV: production

workflows:
  release_staging:
    jobs:
      - release_staging:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              only: /^master$/
  release_production:
    jobs:
      - release_production:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
