name: k8s_deploy
description: Deploy to Kubernetes
inputs:
  K8S_VERSION:
    description: Kubernetes version
    required: true
  K8S_NAMESPACE:
    description: Kubernetes namespace
    required: false
    default: 'deriv-com-api-staging'
  CA_CRT:
    description: Kubernetes CA certificate
    required: true
  KUBE_SERVER:
    description: Kubernetes server
    required: true
  SERVICEACCOUNT_TOKEN:
    description: Kubernetes service account token
    required: true
  DOCKERHUB_ORGANISATION:
    description: Dockerhub organisation
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment variables
      run: |
        echo "NAMESPACE=${{ inputs.K8S_NAMESPACE }}" >> "$GITHUB_ENV"
        echo "KUBE_SERVER=${{ inputs.KUBE_SERVER }}" >> "$GITHUB_ENV"
        echo "SERVICEACCOUNT_TOKEN=${{ inputs.SERVICEACCOUNT_TOKEN }}" >> "$GITHUB_ENV"
        echo "DOCKERHUB_ORGANISATION=${{ inputs.DOCKERHUB_ORGANISATION }}" >> "$GITHUB_ENV"
        echo "CA_CRT=${{ inputs.CA_CRT }}" >> "$GITHUB_ENV"
        echo "APP_NAME=deriv-com-api" >> "$GITHUB_ENV"
      shell: bash
    - name: Deploying to k8s cluster for service ${{ inputs.K8S_NAMESPACE }} 🚀
      run: |
        git clone https://github.com/binary-com/devops-ci-scripts
        cd devops-ci-scripts/k8s-build_tools
        echo ${{ inputs.CA_CRT }} | base64 --decode > ca.crt
        export CA="ca.crt"
        ./release.sh ${APP_NAME} ${{ inputs.K8S_VERSION }}
      shell: bash
