name: notify_slack
description: Send Slack notification
inputs:
  SLACK_WEBHOOK_URL:
    description: Slack webhook URL
    required: true
  MESSAGE:
    description: 'Status message'
    required: true
runs:
  using: composite
  steps:
    - name: Send Slack Notification
      uses: 'deriv-com/shared-actions/.github/actions/send_slack_notification@master'
      with:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        MESSAGE: ${{ inputs.MESSAGE }}

