name: Setup Node
description: Sets up Node.js
runs:
  using: composite
  steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
      with:
        node-version: 16.x
