name: versioning
description: Generates a version for the build
inputs:
  version_name:
    description: Version name
    required: false
    default: staging
runs:
  using: composite
  steps:
    - name: Tag build
      run: echo "${{ inputs.version_name }} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > build/version
      shell: bash
