name: versioning
description: Generates a version for the build
inputs:
  RELEASE_TYPE:
    description: Release Type
    required: false
    default: staging
runs:
  using: composite
  steps:
    - name: Tag build
      run: echo "${{ inputs.RELEASE_TYPE }} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > build/version
      shell: bash
