name: Coveralls Workflow
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # TODO: Replace this with the appropriate runner for Deriv-Api-Docs when provided
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Install dependencies
        uses: './.github/actions/npm_install_from_cache'
      - name: Build
        uses: ./.github/actions/build
      - name: Run Tests
        run: npm run test  -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
