name: Deriv Api Docs Production Workflow
on:
  push:
    tags:
      - production_v*
jobs:
  build_and_publish:
    name: Builds and Publishes to Cloudflare Pages Production
    environment: Production
    runs-on: Runner_16cores_Deriv-app # TODO: Replace this with the appropriate runner for Deriv-Api-Docs when provided
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup_node
      - name: Install dependencies
        uses: ./.github/actions/npm_install_from_cache
      - name: Build
        uses: ./.github/actions/build
        with:
          CONTEXT_ARTIFACT_S3_BUCKET: ${{ vars.CONTEXT_ARTIFACT_S3_BUCKET }}
          DATADOG_APPLICATION_ID: ${{ vars.DATADOG_APPLICATION_ID }}
          DATADOG_CLIENT_TOKEN: ${{ vars.DATADOG_CLIENT_TOKEN }}
          NODE_ENV: production
      - name: Versioning
        uses: ./.github/actions/versioning
        with:
          version_name: production
      - name: Read version file
        id: readVersion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Publish to Cloudflare Pages Production
        uses: ./.github/actions/publish_to_pages_production
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          version: ${{ steps.readVersion.outputs.version }}
  send_slack_notification:
    name: Send Slack Notification
    environment: Production
    runs-on: Runner_16cores_Deriv-app # TODO: Replace this with the appropriate runner for Deriv-Api-Docs when provided
    if: always()
    needs:
      - build_and_publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v3
      - name: Send Slack Notification
        uses: ./.github/actions/notify_slack
        with:
          release_type: Production
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          version: $(echo cat build/version | bash)
