name: Deriv Api Docs Staging Workflow
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    name: Builds and Publishes to Cloudflare Pages Staging
    runs-on: Runner_16cores_Deriv-app # TODO: Replace this with the appropriate runner for Deriv-Api-Docs when provided
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup_node
      - name: Install Dependencies
        uses: ./.github/actions/npm_install_from_cache
      - name: Build
        uses: ./.github/actions/build
        with:
          NODE_ENV: staging
      - name: Publish to Cloudflare Pages Staging
        uses: ./.github/actions/publish_to_pages_staging
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
