name: publish_to_pages
description: Publishes to cloudflare pages
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: Cloudflare account id
    required: true
  CLOUDFLARE_API_TOKEN:
    description: Cloudflare token
    required: true
  CF_BRANCH:
    description: Cloudflare branch
    required: true
  PROJECT_NAME:
    description: Cloudflare project name
    required: true
runs:
  using: composite
  steps:
    - name: Publish to cloudflare pages (staging)
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CF_BRANCH: ${{ inputs.CF_BRANCH }}
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
      run: |-
        npm i wrangler@3.10.1
        cd build
        npx wrangler pages deploy . --project-name=$PROJECT_NAME --branch=$CF_BRANCH
        echo "New staging website - https://$CF_BRANCH-api.deriv.com/"
      shell: bash
