name: publish_to_pages
description: Publishes to cloudflare pages
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: Cloudflare account id
    required: true
  CLOUDFLARE_API_TOKEN:
    description: Cloudflare token
    required: true
  CF_BRANCH:
    description: Cloudflare branch
    required: true
runs:
  using: composite
  steps:
    - name: Publish to cloudflare pages (staging)
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      run: |-
        npm i wrangler@3.10.1
        cd build
        npx wrangler pages deploy . --project-name=deriv-developers-portal-pages --branch=${{ inputs.CF_BRANCH }}
        echo "New staging website - https://staging-api.deriv.com/"
      shell: bash
